repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md,markdown
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black
          - --line-length=120

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --line-length=120

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
        types: [ python ]
        args:
          - --errors-only
          - --disable=import-error
          -
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.5.0
#    hooks:
#      - id: mypy
#        additional_dependencies: [ types-requests, pydantic ]
#        name: mypy
#        entry: mypy
#        language: python
#        types: [ python ]
#        require_serial: true
#        args:
#          - --strict
#          - --ignore-missing-imports
#          - --allow-untyped-decorators
#          - --python-version=3.11
